### ISSUE TITLE
Installation problem [Arch-linux]

### ISSUE THREAD

**Issue by lolrida** [vyvir/AltLinux#23]
I have a problem in the installation, because once I do "python3 main.py" it gives me a series of problems.

![Screenshot_20240518_131159](https://github.com/i-love-altlinux/AltLinux/assets/97251836/6a30d247-b3c5-49e8-92e0-a2cb05296cf8)

**Comment by vyvir** [comment]
Hi, install libhandy:
`sudo pacman -S libhandy`
