### ISSUE TITLE
Doesn't do anything in Arch

### ISSUE THREAD

**Issue by MrArdillo** [vyvir/AltLinux#6]
With all dependencies installed it doesn't install the store

**Comment by yourfriendoss** [comment]
I'm going to need more information.

**Comment by hasanjones** [comment]
I can confirm this issue as well. All dependencies listed are installed.

running python3 main.py gives:

Traceback (most recent call last):
  File "/home/user/AltLinux/main.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by petejones7** [comment]
I can confirm this issue as well. All dependencies listed are installed.

running python3 main.py gives:

Traceback (most recent call last):
File "/home/user/AltLinux/main.py", line 9, in
import requests
ModuleNotFoundError: No module named 'requests'

**Comment by petejones7** [comment]
Running "pip install requests" solves that issue and the splash screen appears, but never connects to anisette server.

**Comment by MrArdillo** [comment]
Hi! No, its fixed with the last version apparently. Thanks!
